


# idade = int(input('digite a idade do carro'))

# if  idade <=3:
#     print(' carro e novo')
    
# elif idade<= 5:
#     print('semi novo')
# elif idade <=10:
#     print('carro velho')
# else:
#     print('Muito velho')    
    

# triangulo = int(input(' digite a quantidades de lados que tem no triangulo'))

# if triangulo ==  3:
#     print('Esse triangulo e um Equilatero')
# elif triangulo == 2:
#     print('esse triangulo e Isoceles')
# else:
#     print('Esse triangulo e Escaleno')
    
    
# numero = int(input('digite o numero'))

# if numero <=1:
#     print('esse numero baixo')
# elif numero <=9:
#     print('esse e numero medio')
# else:
#     print('esse e numero maximo')


# perguntas = int(input('telefonou para a vitimia digite 1 Esteve no Local do Crime digite 2 Mora perto da vitima digite 3 Devia para a vitma digite 4 Ja trabalhou com a vitima digite 5 '))

# if perguntas == 1:
#    print('inocente')
# elif perguntas == 2:
#     print('suspeita')
# elif perguntas == 3 and  perguntas == 4:
#     print('Cumplice do Crime')
# elif perguntas == 5:
#     print('Assasino')
    
    
             