










# for i in range (1, 11):
#  print(i)
 

# for Python in range (5):
#     print('Python')
    
    
# tabuada = 7
# for i in range (1, 11):
#     print(f'{tabuada} x {i} = {tabuada * i} ') 
    

# palavra = input('digite a palavra que deseja')

# for caracterein in palavra:
#     print(palavra)
    
    
# palavra =  input('digite a palavra')

# for letra in palavra:
#     if letra not in 'aeiou':
#         print(f'A primeira consoante encontrada na plavra é {letra}')
        
        
palavra = input('digite a palavra')
vogais = a,e,i,o,

for letra in palavra
    if 